modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="minecraft_quest_ai"
version="1.0.0"
displayName="Minecraft Quest AI"
authors="CMPM Dev Team"
description='''
A simple quest system for Minecraft.
Allows players to complete quests and earn rewards.
'''

[[dependencies.minecraft_quest_ai]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.minecraft_quest_ai]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
